theme = "plain"
icons = "awesome"

[[block]]
block = "xrandr"
icons = true
resolution = true
interval = 2


[[block]]
block = "networkmanager"
on_click = "gnome-terminal -e nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []

[[block]]
block = "music"
on_collapsed_click = "spotify"
dynamic_width = true
buttons = ["prev", "play", "next"]

[[block]]
block = "battery"
interval = 10
format = "{percentage:6#100} {percentage} {time}"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m/%Y %R"
